# Generated by Django 6.0.3 on 2026-03-08 03:58

import django.db.models.deletion
import sgpc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(default=sgpc.models.generar_folio, editable=False, max_length=20, unique=True)),
                ('nombre_fallecido', models.CharField(max_length=200)),
                ('nombre_declarante', models.CharField(max_length=200)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('revision', 'En Revisión'), ('accion_requerida', 'Acción Requerida'), ('aprobado', 'Aprobado')], default='pendiente', max_length=20)),
                ('url_permiso_final', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Trámite',
                'verbose_name_plural': 'Trámites',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('INE_Fallecido', 'INE Fallecido'), ('Certificado_Defuncion', 'Certificado de Defunción'), ('Acta_Defuncion', 'Acta de Defunción'), ('Orden_Inhumacion', 'Orden de Inhumación'), ('INE_Declarante', 'INE del Declarante'), ('Recibo_Pirotecnia', 'Recibo de Pirotecnia'), ('Recibo_Semana_Santa', 'Recibo de Semana Santa'), ('Recibo_Fiestas_Patrias', 'Recibo de Fiestas Patrias'), ('Recibo_Agua', 'Recibo de Agua Potable'), ('Recibo_Cooperaciones', 'Recibo de Cooperaciones')], max_length=50)),
                ('ruta_supabase', models.URLField(max_length=500)),
                ('validado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, help_text='Motivo del rechazo para que el usuario lo vea', null=True)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='sgpc.tramite')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
