# Generated by Django 6.0.3 on 2026-04-03 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre_finado', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('nombre_declarante', models.CharField(max_length=255)),
                ('parentesco', models.CharField(max_length=100)),
                ('email_declarante', models.EmailField(blank=True, max_length=255, null=True)),
                ('telefono_declarante', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDIENTE', 'En Revisión'), ('RECHAZADO', 'Acción Requerida'), ('APROBADO', 'Aprobado'), ('FINALIZADO', 'Permiso Generado')], default='PENDIENTE', max_length=20)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100)),
                ('archivo_url', models.URLField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='sgpc.tramite')),
            ],
        ),
    ]
