# Generated by Django 6.0.3 on 2026-03-27 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgpc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tramite',
            options={},
        ),
        migrations.RemoveField(
            model_name='documento',
            name='validado',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='correo_contacto',
        ),
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('aprobado', 'Aprobado ✅'), ('rechazado', 'Rechazado ❌')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='revisado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_hechas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tramite',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mis_tramites', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='estatus',
            field=models.CharField(choices=[('borrador', 'En Registro'), ('revision', 'Esperando Revisión Admin'), ('accion_requerida', 'Documentos Rechazados'), ('aprobado', 'Finalizado / Permiso Liberado')], default='borrador', max_length=20),
        ),
    ]
