# Generated by Django 6.0.3 on 2026-04-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgpc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='acta_defuncion',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='cert_defuncion',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='ine_declarante',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='ine_fallecido',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='obs_acta_defuncion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='obs_cert_defuncion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='obs_ine_declarante',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='obs_ine_fallecido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='obs_orden_inhumacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='obs_recibo_agua',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='obs_recibo_extras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='obs_recibo_patronales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='obs_recibo_piro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='obs_recibo_ss',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='orden_inhumacion',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='permiso_final',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='recibo_agua',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='recibo_extras',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='recibo_patronales',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='recibo_pirotecnia',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='recibo_semana_santa',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='status_acta_defuncion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='tramite',
            name='status_cert_defuncion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='tramite',
            name='status_ine_declarante',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='tramite',
            name='status_ine_fallecido',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='tramite',
            name='status_orden_inhumacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='tramite',
            name='status_recibo_agua',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='tramite',
            name='status_recibo_extras',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='tramite',
            name='status_recibo_patronales',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='tramite',
            name='status_recibo_piro',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='tramite',
            name='status_recibo_ss',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
