# Generated by Django 6.0.3 on 2026-04-22 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgpc', '0002_tramite_acta_defuncion_tramite_cert_defuncion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramite',
            old_name='permiso_final',
            new_name='pdf_permiso',
        ),
    ]
